######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 26 11:41:53 2016
######################################################################

TEMPLATE = lib
TARGET = smiley
CONFIG(x64){
TARGET = $$TARGET"64"
}
DEPENDPATH += .
INCLUDEPATH += .


CONFIG += staticlib

dir = ../..
include($$dir/common.pri)

# Input
HEADERS += ../../controls.extend/smiley/SSmileyCtrl.h
SOURCES += SSmileyCtrl.cpp